name: my-first workflow
run-name: ${{ github.actor }} is testing out GitHub Actions ðŸš€
on:
    workflow_dispatch
      
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - run:
                echo "Hello, Your pipeline is running.."

    event-name:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - run : echo "Event name is ${{github.event_name}}"
        

